### ISSUE TITLE
listOnce only returns single level children

### ISSUE THREAD

**Issue by zmink-pxc** [IOT-DSA/sdk-dslink-ts#1]
Calling requester.listOnce returns empty map for children of children of root node.

The following screenshot shows listOnce called on root node ('/') of the broker.  Children have empty maps for their corresponding children.

![image](https://user-images.githubusercontent.com/45803332/52823458-d5500000-3069-11e9-8c15-934de289e036.png)

**Comment by rinick** [comment]
this is by design.
list method only shows one layer of children. it can't recursively get the entire tree.
you can send another list request on the child node
