### ISSUE TITLE
Package uses the same npm package name as previous Javascript SDK

### ISSUE THREAD

**Issue by ghost** [IOT-DSA/sdk-dslink-ts#13]
Hi,

Thanks for your work on this - it is most appreciated.

This package has recently reverted from using the name 'dslink-js' to now using the same package name as the previous Javascript SDK in npm 'dslink', which means that any project that relies upon the older SDK as a dependency will fail to run unless it specifically requests version 1.2.1.
Would it be worth adding a note to the project Read Me to highlight this?
Also installing the v1.2.1 of the old SDK gives a warning 'Deprecated in favor of new dslink-js package by @rinick' which is now incorrect

Thanks

Ross

**Comment by rinick** [comment]
you are right, since we've moved the new sdk back to dslink package, we can un-deprecate 1.x.x versions now.

old project should already have `"dslink": "^1.2.1"` in their dependency which should be fine even after we release the 2.0 sdk
