### ISSUE TITLE
Loading data from nodes.json

### ISSUE THREAD

**Issue by zmink-pxc** [IOT-DSA/sdk-dslink-ts#17]
What's the proper way to load data from nodes.json with this sdk?

**Comment by rinick** [comment]
sorry for not having enough documentation on that, for now the documentation is only focus on requester related feature

to save nodes, you can try this example:

https://github.com/IOT-DSA/sdk-dslink-ts/blob/master/example/nodejs-responder/value-node.js
the option is : `saveNodes: true`

if you extend the BaseLocalNode  class, override these functions to control which children/configs/attribute to serialize
https://github.com/IOT-DSA/sdk-dslink-ts/blob/master/ts/src/responder/base-local-node.ts

common nodes that never changes should not be serialized, like the ActionNode, they should be created in parent node's initialize() function
nodes that can't be added/removed but can have internal changes should also be created in initialize(), and they should implement save related api ( easy way to do that is to extend BaseLocalNode or ValueNode)

**Comment by zmink-pxc** [comment]
Hey @rinick thanks for the response.  Saving/generating the nodes.json makes sense, but for the nodejs responder, does the sdk have a .load() function to pull in the last known data structure in for the root node/link from the nodes.json?  I recall the old javascript sdk had a load/init function to reload the nodes.json state on boot up.  Is there something similar with this sdk?

**Comment by rinick** [comment]
@zmink-pxc when saveNodes is true, it automatically load nodes in the constructor
