### ISSUE TITLE
Re-list cached node

### ISSUE THREAD

**Issue by zmink-pxc** [IOT-DSA/sdk-dslink-ts#26]
I've noticed an issue with using a requester to relist a remote node.  After a target remote node/dslink node structure changes, updates for this structure change are not returned.  After relisting the target root dslink node, I'd expect the structure to appear, but it does not.  I used the internal resetNodeCache function on a remote node to attempt to clear the cache so that a new list would force an update to the cache, but this doesn't work as I was hoping.  The only way to get the changes to the target node structure to be available on the Requester is to disconnect and reconnect altogether.  Is there a function I'm missing that will force list the target remoteNode?  Perhaps the caching features don't properly clear the list callbacks?

**Comment by rinick** [comment]
when this happens, do you see the change shown properly in dglux? it could be the responder dslink itself not properly sending the update until it's listed again.

**Comment by zmink-pxc** [comment]
I see the tree update after closing and reopening the root dslink node in dglux.  I'm assuming this is because dglux is relisting the root node, but when doing this with this lib, I don't receive/see any changes..  For reference, the target dslink which is having this issue is the cpp dslink v1.

**Comment by rinick** [comment]
> I see the tree update after closing and reopening the root dslink node in dglux. I'm assuming this is because dglux is relisting the root node, but when doing this with this lib, I don't receive/see any changes.. For reference, the target dslink which is having this issue is the cpp dslink v1.

is it the c sdk? I'm not sure if it handles dynamic add/remove children correctly, it's probably designed mostly to handle static node structure.

**Comment by zmink-pxc** [comment]
Yeah, it's the c sdk.  It has the functionality necessary to delete, and generally seems to work, though it shouldn't really need dglux to relist the root node in order for the tree to update, but I'm not certain exactly how it SHOULD work according to the DSA spec.  As for this lib, is there no way to clear the node cache or force a list call?  Looking through the code briefly, it seems the cache handles all node info requests.

**Comment by rinick** [comment]
List is supposed to be cached, even you clean it in requester side, it might still be cached in broker.
so the responder dslink has to make sure it sends the update to existing list request stream.

**Comment by zmink-pxc** [comment]
Got it, i'll look into that @rinick Does the new v2 dslink cpp support v1 and is it relatively stable?

**Comment by rinick** [comment]
> Got it, i'll look into that @rinick Does the new v2 dslink cpp support v1 and is it relatively stable?

no it's not, and v2 cpp sdk doesn't work with the dart broker. 
we've decide to deprecate the v2 protocol because it breaks backward compatibility.

but all the java v2 related projects work for both v1 and v2 protocol. so those are still supported
