### ISSUE TITLE
Monitor WS Connection

### ISSUE THREAD

**Issue by zachmink** [IOT-DSA/sdk-dslink-ts#7]
@rinick would you support adding a ws connection monitoring functionality?  I don't see a means to monitor connection statuses such as connected, connection lost, or reconnected events.

**Comment by rinick** [comment]
ok, I will add those features.

**Comment by rinick** [comment]
@zachmink , please check this example
 https://github.com/IOT-DSA/sdk-dslink-ts/blob/master/example/nodejs-common/connect-disconnect.js
